routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});


Auth::routes();

Route::group([
    'middleware' => 'auth'
], function ($router) {
    Route::get('/home', 'HomeController@index');
    Route::get('respondents/travelers', 'RespondentController@travelers')->name('respondents.travelers');
    Route::get('respondents/expertises', 'RespondentController@expertises')->name('respondents.expertises');
    Route::get('respondents/scores', 'RespondentController@scores')->name('respondents.scores');
    Route::get('decisions/scores/{key}', 'DecisionController@scores')->name('decisions.scores');
    Route::get('decisions/scores2/{key}', 'DecisionController@scores2')->name('decisions.scores2');

    Route::resource('respondents', 'RespondentController');
    Route::resource('respondentInfos', 'RespondentInfoController');
    Route::resource('decisions', 'DecisionController');
    Route::resource('comparisons', 'ComparisonController');
});

app/Models/Respondent.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Respondent
 * @package App\Models
 * @version July 25, 2019, 2:43 pm UTC
 *
 * @property string name
 * @property string phone
 * @property string respondent_type
 * @property integer traveling_budget
 * @property string start_date
 * @property string end_date
 */
class Respondent extends Model
{
    use SoftDeletes;

    public $table = 'respondents';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'user_id',
        'number_of_person',
        'traveling_budget',
        'day',
        'night',
        'start_date',
        'end_date',
        'city'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'xid' => 'string',
        'name' => 'string',
        'phone' => 'string',
        'respondent_type' => 'string',
        'number_of_person' => 'integer',
        'traveling_budget' => 'integer',
        'day' => 'integer',
        'night' => 'integer',
        'start_date' => 'date',
        'end_date' => 'date',
        'city' => 'city'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    public function formattedBudget() {
        return \App\Helpers\CurrencyHelper::formatCurrency($this->traveling_budget);
    }

    public function users()
    {
        return $this->belongsTo(\App\Models\User::class, 'user_id', 'id');
    }

    public function respondentInfos()
    {
        return $this->hasMany(\App\Models\RespondentInfo::class, 'respondent_id', 'id');
    }

    public function decisions()
    {
        return $this->hasMany(\App\Models\Decision::class, 'respondent_id', 'id');
    }

    /*public function duration() {
        $diff = strtotime($this->end_date) - strtotime($this->start_date);
        return (\round($diff / (60 * 60 * 24)) + 1);
    }*/

    public function duration() {
        return $this->day." day(s) ". $this->night." night(s)";
    }

    public function period() {
        return \App\Helpers\DateHelper::formatDate($this->start_date). ' - '. \App\Helpers\DateHelper::formatDate($this->end_date);
    }
}

app/Http/Controllers/RespondentController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\RespondentDataTable;
use App\DataTables\TravelerDataTable;
use App\DataTables\ExpertiseDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateRespondentRequest;
use App\Http\Requests\UpdateRespondentRequest;
use App\Repositories\RespondentRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class RespondentController extends AppBaseController
{
    /** @var  RespondentRepository */
    private $respondentRepository;

    public function __construct(RespondentRepository $respondentRepo)
    {
        $this->respondentRepository = $respondentRepo;
    }

    /**
     * Display a listing of the Respondent.
     *
     * @param RespondentDataTable $respondentDataTable
     * @return Response
     */
    public function index(RespondentDataTable $respondentDataTable)
    {
        return $respondentDataTable->render('respondents.index');
    }

    public function travelers(TravelerDataTable $travelerDataTable)
    {
        return $travelerDataTable->render('respondents.index');
    }

    public function expertises(ExpertiseDataTable $expertiseDataTable)
    {
        return $expertiseDataTable->render('respondents.index');
    }

    /**
     * Show the form for creating a new Respondent.
     *
     * @return Response
     */
    public function create()
    {
        $count = \App\Models\Respondent::where('respondent_type', 'Expertise')->count() + 1;
        $xid = "EXP{$count}";
        return view('respondents.create', compact('xid'));
    }

    /**
     * Store a newly created Respondent in storage.
     *
     * @param CreateRespondentRequest $request
     *
     * @return Response
     */
    public function store(CreateRespondentRequest $request)
    {
        $input = $request->all();

        $respondent = $this->respondentRepository->create($input);

        Flash::success('Expertise saved successfully.');

        return redirect(route('respondents.expertises'));
    }

    /**
     * Display the specified Respondent.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $respondent = $this->respondentRepository->find($id);

        if (empty($respondent)) {
            Flash::error('Respondent not found');

            return redirect(route('respondents.index'));
        }

        return view('respondents.show')->with('respondent', $respondent);
    }

    /**
     * Show the form for editing the specified Respondent.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $respondent = $this->respondentRepository->find($id);

        if (empty($respondent)) {
            Flash::error('Respondent not found');

            return redirect(route('respondents.index'));
        }

        $xid = $respondent->xid;

        return view('respondents.edit', compact('xid'))->with('respondent', $respondent);
    }

    /**
     * Update the specified Respondent in storage.
     *
     * @param  int              $id
     * @param UpdateRespondentRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRespondentRequest $request)
    {
        $respondent = $this->respondentRepository->find($id);

        if (empty($respondent)) {
            Flash::error('Respondent not found');

            return redirect(route('respondents.index'));
        }

        $respondent = $this->respondentRepository->update($request->all(), $id);

        Flash::success('Expertise updated successfully.');

        return redirect(route('respondents.expertises'));
    }

    /**
     * Remove the specified Respondent from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $respondent = $this->respondentRepository->find($id);

        if (empty($respondent)) {
            Flash::error('Respondent not found');

            return redirect(route('respondents.index'));
        }

        $this->respondentRepository->delete($id);

        Flash::success('Expertise deleted successfully.');

        return redirect(route('respondents.expertises'));
    }

    public function scores()
    {
        $titles = ['Geophysical-Landscape-Aesthetic', 'Ecological-Biological', 'Cultural-Historical', 'Recreational'];
        return view('respondents.scores', compact('titles'));
    }
}

resources/views/respondents/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Respondent
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'respondents.store']) !!}

                        @include('respondents.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/respondents/datatables_actions.blade.php
{!! Form::open(['route' => ['respondents.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('respondents.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @if(Request::is('respondents/expertises*'))
    <a href="{{ route('respondents.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endif
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/respondents/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Respondent
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($respondent, ['route' => ['respondents.update', $respondent->id], 'method' => 'patch']) !!}

                        @include('respondents.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/respondents/fields.blade.php
{!! Form::hidden('respondent_type', "Expertise") !!}

<div class="row">
    <div class="col-md-12">
        <!-- Name Field -->
        <div class="form-group col-sm-6">
            {!! Form::label('xid', 'Expertise ID:') !!}
            {!! Form::text('xid', $xid, ['class' => 'form-control', 'readonly']) !!}
        </div>
    </div>
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('city', 'City:') !!}
    {!! Form::select('city', ['Bandung' => 'Bandung', 'Yogyakarta' => 'Yogyakarta', 'Banyuwangi' => 'Banyuwangi', 'Bali' => 'Bali', 'Bali' => 'Bali', 'Malaka' => 'Malaka'], null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('respondents.expertises') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/respondents/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Respondents</h1>
        <h1 class="pull-right">
            @if(Request::is('respondents/expertises*'))
            <a class="btn btn-primary" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('respondents.create') !!}">Add New</a>&nbsp;
            <a class="btn btn-success pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('respondents.scores') !!}">Total Score</a>
            @endif
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('respondents.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/respondents/scores.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Expertises
        </h1>
    </section>
    <div class="content form-horizontal">
        <div class="box box-primary">
            <div class="box-body">
                <div class="box-header">
                    <h3 class="box-title">Scores</h3>
                </div>
                <div class="box-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th width="20">No</th>
                                <th>Title</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($titles as $k=>$title)
                            <tr>
                                <td>{{ $k + 1}}</td>
                                <td>{{ $title }}</td>
                                <td><a href="{{ route('decisions.scores', urlencode($title)) }}" class='btn btn-default btn-xs'>
                                        <i class="glyphicon glyphicon-eye-open"></i>
                                    </a> &nbsp;<a href="{{ route('decisions.scores2', urlencode($title)) }}" class='btn btn-success btn-xs'>
                                            <i class="glyphicon glyphicon-eye-open"></i>
                                        </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/respondents/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Respondent
        </h1>
    </section>
    <div class="content form-horizontal">
        @include('respondents.show_fields')
    </div>
@endsection

resources/views/respondents/show_fields.blade.php
<div class="box box-primary">
    <div class="box-body">
        <div class="box-header">
            <h3 class="box-title">Detail</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="form-group col-md-6">
                    {!! Form::label('name', 'Name', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('name', $respondent->name, ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>

                <div class="form-group col-md-6">
                    {!! Form::label('city', 'City', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('city', $respondent->city, ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>
                <div class="form-group col-md-6">
                    {!! Form::label('phone', 'Phone', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('phone', $respondent->phone, ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>
                <div class="form-group col-md-6">
                    {!! Form::label('respondent_type', 'Respondent Type', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('respondent_type', $respondent->respondent_type, ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>
                @if($respondent->respondent_type == 'Traveller')
                <div class="form-group col-md-6">
                    {!! Form::label('number_of_person', 'Person', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('number_of_person', $respondent->number_of_person, ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>
                <div class="form-group col-md-6">
                    {!! Form::label('traveling_budget', 'Budget', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('traveling_budget', $respondent->formattedBudget(), ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>

                <div class="form-group col-md-6">
                    {!! Form::label('duration', 'Duration', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('duration', $respondent->duration(), ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>

                <div class="form-group col-md-6">
                    {!! Form::label('period', 'Period', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('period', $respondent->period(), ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>

@if($respondent->respondent_type == 'Traveller')
<div class="box box-primary">
    <div class="box-body">
        <div class="box-header">
            <h3 class="box-title">Genders and Ages</h3>
        </div>
        <div class="box-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th width="20">No</th>
                        <th>Gender</th>
                        <th>Age</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($respondent->respondentInfos as $k=>$info)
                    <tr>
                        <td>{{ $k + 1}}</td>
                        <td>{{ $info->gender }}</td>
                        <td>{{ $info->age}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endif

<div class="box box-primary">
    <div class="box-body">
        <div class="box-header">
            <h3 class="box-title">Scores</h3>
        </div>
        <div class="box-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th width="20">No</th>
                        <th>Title</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($respondent->decisions as $k=>$decision)
                    <tr>
                        <td>{{ $k + 1}}</td>
                        <td>{{ $decision->title }}</td>
                        <td><a href="{{ route('decisions.show', $decision->id) }}" class='btn btn-default btn-xs'>
                                <i class="glyphicon glyphicon-eye-open"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="box box-primary">
    <div class="box-body">
        <div class="box-header">
            <h3 class="box-title">Timestamps</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <!-- Created At Field -->
                <div class="form-group col-md-6">
                    {!! Form::label('created_at', 'Created At', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('campaign_id', \Carbon\Carbon::parse($respondent->created_at)->format('d M Y H:i:s'), ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>

                <!-- Updated At Field -->
                <div class="form-group col-md-6">
                    {!! Form::label('updated_at', 'Updated At', ['class' => 'col-sm-4 control-label']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('campaign_id', \Carbon\Carbon::parse($respondent->updated_at)->format('d M Y H:i:s'), ['class' => 'form-control', 'readonly']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/respondents/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection