routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});


Auth::routes();

Route::group([
    'middleware' => 'auth'
], function ($router) {
    Route::get('/home', 'HomeController@index');
    Route::get('respondents/travelers', 'RespondentController@travelers')->name('respondents.travelers');
    Route::get('respondents/expertises', 'RespondentController@expertises')->name('respondents.expertises');
    Route::get('respondents/scores', 'RespondentController@scores')->name('respondents.scores');
    Route::get('decisions/scores/{key}', 'DecisionController@scores')->name('decisions.scores');
    Route::get('decisions/scores2/{key}', 'DecisionController@scores2')->name('decisions.scores2');

    Route::resource('respondents', 'RespondentController');
    Route::resource('respondentInfos', 'RespondentInfoController');
    Route::resource('decisions', 'DecisionController');
    Route::resource('comparisons', 'ComparisonController');
});

app/Models/RespondentInfo.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class RespondentInfo
 * @package App\Models
 * @version July 25, 2019, 2:43 pm UTC
 *
 * @property \App\Models\Respondent respondent
 * @property integer respondent_id
 * @property string gender
 * @property integer age
 */
class RespondentInfo extends Model
{
    use SoftDeletes;

    public $table = 'respondent_infos';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'respondent_id',
        'gender',
        'age'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'respondent_id' => 'integer',
        'gender' => 'string',
        'age' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function respondent()
    {
        return $this->belongsTo(\App\Models\Respondent::class, 'respondent_id', 'id');
    }
}

app/Http/Controllers/RespondentInfoController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\RespondentInfoDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateRespondentInfoRequest;
use App\Http\Requests\UpdateRespondentInfoRequest;
use App\Repositories\RespondentInfoRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class RespondentInfoController extends AppBaseController
{
    /** @var  RespondentInfoRepository */
    private $respondentInfoRepository;

    public function __construct(RespondentInfoRepository $respondentInfoRepo)
    {
        $this->respondentInfoRepository = $respondentInfoRepo;
    }

    /**
     * Display a listing of the RespondentInfo.
     *
     * @param RespondentInfoDataTable $respondentInfoDataTable
     * @return Response
     */
    public function index(RespondentInfoDataTable $respondentInfoDataTable)
    {
        return $respondentInfoDataTable->render('respondent_infos.index');
    }

    /**
     * Show the form for creating a new RespondentInfo.
     *
     * @return Response
     */
    public function create()
    {
        return view('respondent_infos.create');
    }

    /**
     * Store a newly created RespondentInfo in storage.
     *
     * @param CreateRespondentInfoRequest $request
     *
     * @return Response
     */
    public function store(CreateRespondentInfoRequest $request)
    {
        $input = $request->all();

        $respondentInfo = $this->respondentInfoRepository->create($input);

        Flash::success('Respondent Info saved successfully.');

        return redirect(route('respondentInfos.index'));
    }

    /**
     * Display the specified RespondentInfo.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $respondentInfo = $this->respondentInfoRepository->find($id);

        if (empty($respondentInfo)) {
            Flash::error('Respondent Info not found');

            return redirect(route('respondentInfos.index'));
        }

        return view('respondent_infos.show')->with('respondentInfo', $respondentInfo);
    }

    /**
     * Show the form for editing the specified RespondentInfo.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $respondentInfo = $this->respondentInfoRepository->find($id);

        if (empty($respondentInfo)) {
            Flash::error('Respondent Info not found');

            return redirect(route('respondentInfos.index'));
        }

        return view('respondent_infos.edit')->with('respondentInfo', $respondentInfo);
    }

    /**
     * Update the specified RespondentInfo in storage.
     *
     * @param  int              $id
     * @param UpdateRespondentInfoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRespondentInfoRequest $request)
    {
        $respondentInfo = $this->respondentInfoRepository->find($id);

        if (empty($respondentInfo)) {
            Flash::error('Respondent Info not found');

            return redirect(route('respondentInfos.index'));
        }

        $respondentInfo = $this->respondentInfoRepository->update($request->all(), $id);

        Flash::success('Respondent Info updated successfully.');

        return redirect(route('respondentInfos.index'));
    }

    /**
     * Remove the specified RespondentInfo from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $respondentInfo = $this->respondentInfoRepository->find($id);

        if (empty($respondentInfo)) {
            Flash::error('Respondent Info not found');

            return redirect(route('respondentInfos.index'));
        }

        $this->respondentInfoRepository->delete($id);

        Flash::success('Respondent Info deleted successfully.');

        return redirect(route('respondentInfos.index'));
    }
}

resources/views/respondent_infos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Respondent Info
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'respondentInfos.store']) !!}

                        @include('respondent_infos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/respondent_infos/datatables_actions.blade.php
{!! Form::open(['route' => ['respondentInfos.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('respondentInfos.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('respondentInfos.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/respondent_infos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Respondent Info
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($respondentInfo, ['route' => ['respondentInfos.update', $respondentInfo->id], 'method' => 'patch']) !!}

                        @include('respondent_infos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/respondent_infos/fields.blade.php
<!-- Respondent Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('respondent_id', 'Respondent Id:') !!}
    {!! Form::select('respondent_id', ['s' => 's'], null, ['class' => 'form-control']) !!}
</div>

<!-- Gender Field -->
<div class="form-group col-sm-6">
    {!! Form::label('gender', 'Gender:') !!}
    {!! Form::select('gender', ['Pria' => 'Pria', 'Wanita' => 'Wanita'], null, ['class' => 'form-control']) !!}
</div>

<!-- Age Field -->
<div class="form-group col-sm-6">
    {!! Form::label('age', 'Age:') !!}
    {!! Form::number('age', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('respondentInfos.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/respondent_infos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Respondent Infos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('respondentInfos.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('respondent_infos.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/respondent_infos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Respondent Info
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('respondent_infos.show_fields')
                    <a href="{!! route('respondentInfos.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/respondent_infos/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $respondentInfo->id !!}</p>
</div>

<!-- Respondent Id Field -->
<div class="form-group">
    {!! Form::label('respondent_id', 'Respondent Id:') !!}
    <p>{!! $respondentInfo->respondent_id !!}</p>
</div>

<!-- Gender Field -->
<div class="form-group">
    {!! Form::label('gender', 'Gender:') !!}
    <p>{!! $respondentInfo->gender !!}</p>
</div>

<!-- Age Field -->
<div class="form-group">
    {!! Form::label('age', 'Age:') !!}
    <p>{!! $respondentInfo->age !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $respondentInfo->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $respondentInfo->updated_at !!}</p>
</div>

resources/views/respondent_infos/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection